// Types for the drizzle-kit generated `migrations.js` (regenerated by
// `npm run db:generate`; this declaration is hand-kept alongside it).
declare const migrations: {
  journal: {
    version: string;
    dialect: string;
    entries: {
      idx: number;
      version: string;
      when: number;
      tag: string;
      breakpoints: boolean;
    }[];
  };
  migrations: Record<string, string>;
};

export default migrations;
